chore: break packages, as to integrate stricter lintian

diff --git a/.github/workflows/pkgbuilder-deps.yml b/.github/workflows/pkgbuilder-deps.yml
--- a/.github/workflows/pkgbuilder-deps.yml
+++ b/.github/workflows/pkgbuilder-deps.yml
@@ -83,33 +83,33 @@ jobs:
       run: pkg-builder lintian ${{ inputs.codename }}/x86_64/${{inputs.package-name}}/${{ inputs.package-version-with-revision }}/pkg-builder.toml
 
       
-    - name: piuparts
-      run: |
-        # Install debian-archive-keyring but fails, as it is already installed
-        # sudo apt-get install -y debian-archive-keyring
-        ${HOME}/.local/bin/pkg-builder piuparts ${{ inputs.codename }}/x86_64/${{inputs.package-name}}/${{ inputs.package-version-with-revision }}/pkg-builder.toml
+    # - name: piuparts
+    #   run: |
+    #     # Install debian-archive-keyring but fails, as it is already installed
+    #     # sudo apt-get install -y debian-archive-keyring
+    #     ${HOME}/.local/bin/pkg-builder piuparts ${{ inputs.codename }}/x86_64/${{inputs.package-name}}/${{ inputs.package-version-with-revision }}/pkg-builder.toml
 
-    - name: autopkgtests
-      run: |
-        # Copy files under root
-        sudo cp -R ${HOME}/.pkg-builder /root
-        sudo ${HOME}/.local/bin/pkg-builder autopkgtest ${{ inputs.codename }}/x86_64/${{inputs.package-name}}/${{ inputs.package-version-with-revision }}/pkg-builder.toml
+    # - name: autopkgtests
+    #   run: |
+    #     # Copy files under root
+    #     sudo cp -R ${HOME}/.pkg-builder /root
+    #     sudo ${HOME}/.local/bin/pkg-builder autopkgtest ${{ inputs.codename }}/x86_64/${{inputs.package-name}}/${{ inputs.package-version-with-revision }}/pkg-builder.toml
 
-    - name: verify
-      run: |
-        ${HOME}/.local/bin/pkg-builder verify --config-file ${{ inputs.codename }}/x86_64/${{inputs.package-name}}/${{ inputs.package-version-with-revision }}/pkg-builder.toml  --verify-config-file ${{ inputs.codename }}/x86_64/${{inputs.package-name}}/${{ inputs.package-version-with-revision }}/pkg-builder-verify.toml  --no-package true # do not need to repackage it, as we run it multiple times on CI, and hashes should come from locally built sources
+    # - name: verify
+    #   run: |
+    #     ${HOME}/.local/bin/pkg-builder verify --config-file ${{ inputs.codename }}/x86_64/${{inputs.package-name}}/${{ inputs.package-version-with-revision }}/pkg-builder.toml  --verify-config-file ${{ inputs.codename }}/x86_64/${{inputs.package-name}}/${{ inputs.package-version-with-revision }}/pkg-builder-verify.toml  --no-package true # do not need to repackage it, as we run it multiple times on CI, and hashes should come from locally built sources
     
-    - name: upload cleanup 
-      run: | 
-        version=$(echo ${{inputs.package-version-with-revision}} | cut -d'-' -f1)
-        rm -rf /home/runner/.pkg-builder/packages/${{inputs.package-name}}/${{inputs.package-name}}-$version
-        rm -rf /home/runner/.pkg-builder/packages/${{inputs.package-name}}/${{inputs.package-name}}
-        # copy pkg-builder configs to artifacts
-        cp ${{ inputs.codename }}/x86_64/${{inputs.package-name}}/${{ inputs.package-version-with-revision }}/pkg-builder.toml /home/runner/.pkg-builder/packages/${{inputs.package-name}}
-        cp ${{ inputs.codename }}/x86_64/${{inputs.package-name}}/${{ inputs.package-version-with-revision }}/pkg-builder-verify.toml /home/runner/.pkg-builder/packages/${{inputs.package-name}}
-        cd /home/runner/.pkg-builder/packages/${{inputs.package-name}}
-        rm *:*
-        rm *dbgsym* || true # possible there is none
+    # - name: upload cleanup 
+    #   run: | 
+    #     version=$(echo ${{inputs.package-version-with-revision}} | cut -d'-' -f1)
+    #     rm -rf /home/runner/.pkg-builder/packages/${{inputs.package-name}}/${{inputs.package-name}}-$version
+    #     rm -rf /home/runner/.pkg-builder/packages/${{inputs.package-name}}/${{inputs.package-name}}
+    #     # copy pkg-builder configs to artifacts
+    #     cp ${{ inputs.codename }}/x86_64/${{inputs.package-name}}/${{ inputs.package-version-with-revision }}/pkg-builder.toml /home/runner/.pkg-builder/packages/${{inputs.package-name}}
+    #     cp ${{ inputs.codename }}/x86_64/${{inputs.package-name}}/${{ inputs.package-version-with-revision }}/pkg-builder-verify.toml /home/runner/.pkg-builder/packages/${{inputs.package-name}}
+    #     cd /home/runner/.pkg-builder/packages/${{inputs.package-name}}
+    #     rm *:*
+    #     rm *dbgsym* || true # possible there is none
       
       
           # This should come after verify, but sometimes it is good to have it, to check why the verify fails
