conditionally disable piuparts

diff --git a/.github/workflows/upcoming.yml b/.github/workflows/upcoming.yml
--- a/.github/workflows/upcoming.yml
+++ b/.github/workflows/upcoming.yml
@@ -99,7 +99,7 @@ jobs:
         - name: Create chroot env
           run: |
             cd ${{ steps.env.outputs.tag_name }}
-            sudo ln -s /usr/share/debootstrap/scripts/gutsy /usr/share/debootstrap/scripts/noble
+            #sudo ln -s /usr/share/debootstrap/scripts/gutsy /usr/share/debootstrap/scripts/noble || true
             pkg-builder env create
             echo "${HOME}/.cache/sbuild/${{ steps.env.outputs.codename }}-${{ steps.env.outputs.arch }}.tar.gz" >> $GITHUB_PATH
   
@@ -109,12 +109,13 @@ jobs:
             pkg-builder package --run-piuparts false --run-autopkgtest false --run-lintian true
             echo "${HOME}/.pkg-builder/packages/${{steps.env.outputs.codename}}/${{steps.env.outputs.package_name}}-${{steps.env.outputs.version_number}}" >> $GITHUB_PATH
         
-        # - name: piuparts
-        #   run: |
-        #    # installing debian-archive-keyring fails on ubuntu LTS, not sure why, but it says it is already installed
-        #    # sudo apt install -y debian-archive-keyring
-        #    cd ${{ steps.env.outputs.tag_name }}
-        #    ${HOME}/.local/bin/pkg-builder piuparts
+        - name: piuparts
+          if: steps.env.outputs.codename != 'noble'
+          run: |
+           # installing debian-archive-keyring fails on ubuntu LTS, not sure why, but it says it is already installed
+           # sudo apt install -y debian-archive-keyring
+           cd ${{ steps.env.outputs.tag_name }}
+           ${HOME}/.local/bin/pkg-builder piuparts
   
         - name: autopkgtest
           run: |
